---
title: "Fixed Effects UKHLS"
author: "Emir Zecovic"

format:
  html:
    theme: spacelab
    embed-resources: true
    smooth-scroll: true
    toc: true
    toc-location: left
    page-layout: full
    toc-depth: 6
    toc-title: Contents

number-sections: false

comments:
  hypothesis: false

editor: visual
---

```{r, include=FALSE}
# Setup ----
## Packages ----
# if ("convenience" %in% rownames(installed.packages()) ==F) {
#   devtools::install_github("ratsupaltuf/convenience", force=T)
# }

alabs<- function(x, kable=TRUE, extended=T){
  tb<- tibble(labels=names(attributes(x)$labels), values=attributes(x)$labels)
  
  if(extended==T) {
    lab<- attributes(x)$label
    cl<- class(x)
    u<- unique(x)
    
    if(kable==T) {
      
      cat(lab, "\n",
          "Class:",cl, "\n",
          "Unique values:", u, "\n",
          "\n"
      )
      print(knitr::kable(tb, caption="Labels"))
      
    }  else {
      cat(lab, "\n",
          "Class:",cl, "\n",
          "Unique values:", u, "\n",
          "\n"
      )
      print(tb)
    }
  } else if (kable==T) {
    
    kable(tb)
  }  else {
    tb
  }
}

packages <- c("tidyverse", "haven", "pastecs", "datawizard", #"convenience",
              "ggplot2", "ggalluvial", "ggthemes", "viridis", "ggrepel",
              "sjPlot", "lme4", "knitr", "kableExtra", "gt", "survey",
              "stringr", "flextable", "officer", "sf", "plm", "stargazer",
              "patchwork", "tidytext", "sjlabelled")
install.packages(setdiff(packages, rownames(installed.packages())))
suppressMessages(lapply(packages, library, character.only = TRUE, quietly=T))
rm(packages)
options(max.print=10000)

## Load ----
#uk <- readRDS("C:/Users/Emir  PC/Desktop/PhD/Paper1/PAIRS/data/uk.rds")
uk <- readRDS("~/PAIRS/data/uk.rds")
```

## M1 (Log_HH_Inc_OECD)

```{r}
## M1a ----
M1a <- plm(
  rel_happy ~ log_hhgrslabinc_oecd,
  data = uk,
  index = "pidp",
  model = "within"
)


## M1b ----
M1b <- plm(
  rel_happy ~ log_hhgrslabinc_oecd,
  data = uk,
  index = "pidp",
  model = "within"
)


## M1c ----
M1c <- plm(
  rel_happy ~ log_hhgrslabinc_oecd +
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk,
  index = "pidp",
  model = "within"
)

## M1d ----
M1d <- plm(
  rel_happy ~ log_hhnetinc_oecd +
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk,
  index = "pidp",
  model = "within"
)
```

```{r, echo=FALSE}
stargazer(list(M1a, M1b, M1c, M1d),
          
          column.labels=c("M1a", "M1b", "M1c", "M1d"
                          ),
          
          covariate.labels=c("Equivalence household gross labor income (log)",
                             "Equivalence household net income (log)",
                             "Married (Ref: Cohabiting)",
                             "Full-time employed (Ref. Retired)",
                             "Part-time employed",
                             "Self-employed",
                             "Unemployed",
                             "Inactive",
                             "Number of children (0-10)"
          ),
          align=TRUE,
          type = "text")
```

## M2 (Means-tested benefits)

```{r}
# M2 (Means-tested) ----
## M2a ----
M2a <- plm(
  rel_happy ~ benefit_MT,
  data = uk,
  index = "pidp",
  model = "within"
)


## M2b ----
M2b <- plm(
  rel_happy ~ benefit_MT +
    relstat2 + relevel(lfstat, ref = "Retired") + nchild,
  data = uk,
  index = "pidp",
  model = "within"
)


## M2c ----
M2c <- plm(
  rel_happy ~ benefit_MT +
    relstat2 + relevel(lfstat, ref = "Retired") + nchild +
    factor(wave),
  data = uk,
  index = "pidp",
  model = "within"
)


## M2d ----
M2d <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk,
  index = "pidp",
  model = "within"
)

## M2e ----
M2e <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk,
  index = "pidp",
  model = "within"
)
```

```{r, echo=FALSE}
stargazer(list(M2a, M2b, M2c, M2d, M2e),
          
          column.labels=c("M2a", "M2b", "M2c", "M2d", "M2e"),
          
          covariate.labels=c("Means-tested benefit receipt (0/1)",
                            "Equivalence household gross labor income (log)",
                            "Equivalence household net income (log)",
                            "Married (Ref: Cohabiting)",
                            "Full-time employed (Ref. Retired)",
                            "Part-time employed",
                            "Self-employed",
                            "Unemployed",
                            "Inactive",
                            "Number of children (0-10)"
                             ),
          
          align=TRUE,
          type = "text")
```

# M3 (In-work)

```{r}
uk_emp <- uk %>%
  filter(
    lfstat %in% c(
      "Full-time employed",
      "Part-time employed",
      "Self-employed"
    )
  )


## M3a ----
M3a <- plm(
  rel_happy ~ benefit_MT,
  data = uk_emp,
  index = "pidp",
  model = "within"
)

## M3b ----
M3b <- plm(
  rel_happy ~ benefit_MT +
    relstat2 + lfstat + nchild,
  data = uk_emp,
  index = "pidp",
  model = "within"
)

## M3c ----
M3c <- plm(
  rel_happy ~ benefit_MT +
    relstat2 + lfstat + nchild +
    factor(wave),
  data = uk_emp,
  index = "pidp",
  model = "within"
)

## M3d ----
M3d <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + lfstat + nchild +
    factor(wave),
  data = uk_emp,
  index = "pidp",
  model = "within"
)

## M3e ----
M3e <- plm(
  rel_happy ~ benefit_MT +
    log_hhnetinc_oecd + 
    relstat2 + lfstat + nchild +
    factor(wave),
  data = uk_emp,
  index = "pidp",
  model = "within"
)
```

```{r, echo=FALSE}
stargazer(list(M3a, M3b, M3c, M3d, M3e),
          
          column.labels=c("M3a", "M3b", "M3c", "M3d", "M3e"),
          
          covariate.labels=c("Means-tested benefit receipt (0/1)",
                             "Equivalence household gross labor income (log)",
                             "Equivalence household net income (log)",
                             "Married (Ref: Cohabiting)",
                             "Part-time employed (Ref. Full-time employed)",
                             "Self-employed",
                             "Number of children (0-10)"
          ),
          
          align=TRUE,
          type = "text")
```

## M4 (Out-of-work)

```{r}
uk_unemp <- uk %>%
  filter(
    lfstat %in% c(
      "Unemployed",
      "Retired",
      "Inactive"
    )
  )


## M4a ----
M4a <- plm(
  rel_happy ~ benefit_MT,
  data = uk_unemp,
  index = "pidp",
  model = "within"
)

## M4b ----
M4b <- plm(
  rel_happy ~ benefit_MT +
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild,
  data = uk_unemp,
  index = "pidp",
  model = "within"
)

## M4c ----
M4c <- plm(
  rel_happy ~ benefit_MT +
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild +
    factor(wave),
  data = uk_unemp,
  index = "pidp",
  model = "within"
)

## M4d ----
M4d <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild +
    factor(wave),
  data = uk_unemp,
  index = "pidp",
  model = "within"
)

## M4e ----
M4e <- plm(
  rel_happy ~ benefit_MT +
    log_hhnetinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild +
    factor(wave),
  data = uk_unemp,
  index = "pidp",
  model = "within"
)
```

```{r, echo=FALSE}
stargazer(list(M4a, M4b, M4c, M4d, M4e),
          
          column.labels=c("M4a", "M4b", "M4c", "M4d", "M4e"),
          
          covariate.labels=c("Means-tested benefit receipt (0/1)",
                             "Equivalence household gross labor income (log)",
                             "Equivalence household net income (log)",
                             "Married (Ref: Cohabiting)",
                             "Unemployed (Ref. Inactive)",
                             "Retired",
                             "Number of children (0-10)"
          ),
          
          align=TRUE,
          type = "text")
```

## M5 (Men) & M6 (Women)

```{r}
# M5 (Male) ----
uk_men <- uk %>%
  filter(sex == "Male")

## M5a ----
M5a <- plm(
  rel_happy ~ benefit_MT +
    relstat2 + relevel(lfstat, ref = "Retired") + nchild +
    factor(wave),
  data = uk_men,
  index = "pidp",
  model = "within"
)


## M5b ----
M5b <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk_men,
  index = "pidp",
  model = "within"
)




# M6 (Woman) ----
uk_women <- uk %>%
  filter(sex == "Female")

## M6a ----
M6a <- plm(
  rel_happy ~ benefit_MT +
    relstat2 + relevel(lfstat, ref = "Retired") + nchild +
    factor(wave),
  data = uk_women,
  index = "pidp",
  model = "within"
)


## M6b ----
M6b <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk_women,
  index = "pidp",
  model = "within"
)
```

```{r, echo=FALSE}
stargazer(list(M5a, M5b, M6a, M6b),
          
          column.labels=c("M5a (Men)", "M5b (Men)", "M6a (Women)", "M6b (Women)"
                          ),
          
          covariate.labels=c("Means-tested benefit receipt (0/1)",
                             "Equivalence household gross labor income (log)",
                             "Married (Ref: Cohabiting)",
                             "Full-time employed (Ref. Retired)",
                             "Part-time employed",
                             "Self-employed",
                             "Unemployed",
                             "Inactive",
                             "Number of children (0-10)"
          ),
          
          align=TRUE,
          type = "text")
```

## M7 (In-work + Men/Women) & M8 (Out-of-work + Men/Women)

```{r}
# M7 (In-work + Men/Women) ----
uk_emp_m<- uk_men %>%
  filter(
    lfstat %in% c(
      "Full-time employed",
      "Part-time employed",
      "Self-employed"
    )
  )

uk_emp_w<- uk_women %>%
  filter(
    lfstat %in% c(
      "Full-time employed",
      "Part-time employed",
      "Self-employed"
    )
  )

## M7a ----
M7a <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + lfstat + nchild +
    factor(wave),
  data = uk_emp_m,
  index = "pidp",
  model = "within"
)

## M7b ----
M7b <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + lfstat + nchild +
    factor(wave),
  data = uk_emp_w,
  index = "pidp",
  model = "within"
)





# M8 (Out-of-work + Men/Women) ----
uk_unemp_m <- uk_men %>%
  filter(
    lfstat %in% c(
      "Unemployed",
      "Retired",
      "Inactive"
    )
  )

uk_unemp_w <- uk_women %>%
  filter(
    lfstat %in% c(
      "Unemployed",
      "Retired",
      "Inactive"
    )
  )

## M8a ----
M8a <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild +
    factor(wave),
  data = uk_unemp_m,
  index = "pidp",
  model = "within"
)

## M8b ----
M8b <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild +
    factor(wave),
  data = uk_unemp_w,
  index = "pidp",
  model = "within"
)
```

```{r, echo=FALSE}
stargazer(list(M7a, M7b, M8a, M8b),
          
          column.labels=c("M7a (In-work + Men)", "M7b (In-Work + Women)",
                          "M8a (Out-of-work + Men)", "M8b (Out-of-work + Women)"
                          ),
          
          covariate.labels=c("Means-tested benefit receipt (0/1)",
                             "Equivalence household gross labor income (log)",
                             "Married (Ref: Cohabiting)",
                             "Part-time employed (Ref. Full-time employed)",
                             "Self-employed",
                             "Unemployed (Ref. Inactive)",
                             "Retired",
                             "Number of children (0-10)"
          ),
          
          align=TRUE,
          type = "text")
```

### Bonus: M10 (Dyadic Adjustment Scale: Relationship satisfaction subscale)

```{r}
M10a <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk,
  index = "pidp",
  model = "within"
)

M10b <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + lfstat + nchild +
    factor(wave),
  data = uk_emp,
  index = "pidp",
  model = "within"
)

M10c <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild +
    factor(wave),
  data = uk_unemp,
  index = "pidp",
  model = "within"
)
```

```{r, echo=FALSE}
stargazer(list(M10a, M10b, M10c),
          
          column.labels=c("M10a (all)", "M10b (In-work)", "M10c (Out-of-work)"
          ),
    
          
          align=TRUE,
          type = "text")
```

#### DAS (Men/Women)

```{r}
M11a <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk_men,
  index = "pidp",
  model = "within"
)


M11b <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk_women,
  index = "pidp",
  model = "within"
)
```

```{r, echo=FALSE}
stargazer(list(M11a, M11b),
          
          column.labels=c("M11a (Men)", "M11b (Women)"
          ),
    
          
          align=TRUE,
          type = "text")
```

#### DAS (In-/Out-Work + Men/Women)

```{r}
M100 <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk_emp_m,
  index = "pidp",
  model = "within"
)


M200 <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + 
    factor(wave),
  data = uk_emp_w,
  index = "pidp",
  model = "within"
)




##
M300 <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild +
    factor(wave),
  data = uk_unemp_m,
  index = "pidp",
  model = "within"
)

M400 <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrslabinc_oecd + 
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild +
    factor(wave),
  data = uk_unemp_w,
  index = "pidp",
  model = "within"
)
```

```{r, echo=FALSE}
stargazer(list(M100, M200, M300, M400),
          
          column.labels=c("M100 (In-work + Men)", "M200 (In-Work + Women)",
                          "M300 (Out-of-work + Men)", "M400 (Out-of-work + Women)"
                          ),
    
          
          align=TRUE,
          type = "text")
```
