---
title: "Random Effects UKHLS"
author: "Emir Zecovic"

format:
  html:
    theme: spacelab
    embed-resources: true
    smooth-scroll: true
    toc: true
    toc-location: left
    page-layout: full
    toc-depth: 6
    toc-title: Contents

number-sections: false

comments:
  hypothesis: false

editor: visual
---

```{r, include=FALSE}
# Setup ----
## Packages ----
# if ("convenience" %in% rownames(installed.packages()) ==F) {
#   devtools::install_github("ratsupaltuf/convenience", force=T)
# }

alabs<- function(x, kable=TRUE, extended=T){
  tb<- tibble(labels=names(attributes(x)$labels), values=attributes(x)$labels)
  
  if(extended==T) {
    lab<- attributes(x)$label
    cl<- class(x)
    u<- unique(x)
    
    if(kable==T) {
      
      cat(lab, "\n",
          "Class:",cl, "\n",
          "Unique values:", u, "\n",
          "\n"
      )
      print(knitr::kable(tb, caption="Labels"))
      
    }  else {
      cat(lab, "\n",
          "Class:",cl, "\n",
          "Unique values:", u, "\n",
          "\n"
      )
      print(tb)
    }
  } else if (kable==T) {
    
    kable(tb)
  }  else {
    tb
  }
}

packages <- c("tidyverse", "haven", "pastecs", "datawizard", #"convenience",
              "ggplot2", "ggalluvial", "ggthemes", "viridis", "ggrepel",
              "sjPlot", "lme4", "knitr", "kableExtra", "gt", "survey",
              "stringr", "flextable", "officer", "sf", "plm", "stargazer",
              "patchwork", "tidytext", "sjlabelled")
install.packages(setdiff(packages, rownames(installed.packages())))
suppressMessages(lapply(packages, library, character.only = TRUE, quietly=T))
rm(packages)
options(max.print=10000)

## Load ----
uk <- readRDS("C:/Users/Emir  PC/Desktop/PhD/Paper1/PAIRS/data/uk.rds")
#uk <- readRDS("~/PAIRS/data/uk.rds")
```

## M1 (Log_HH_Inc_OECD)

```{r}
# M1 (Log_HH_Inc_OECD) ----
## M1a ----
M1a <- plm(
  rel_happy ~ log_hhnetinc_oecd,
  data = uk,
  index = "pidp",
  model = "random"
)

## M1b ----
M1b <- plm(
  rel_happy ~ log_hhnetinc_oecd +
    sex + age + ethnicity + education + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + gor_dv + 
    factor(wave),
  data = uk,
  index = "pidp",
  model = "random"
)

## M1c ----
M1c <- plm(
  rel_happy ~ log_hhgrsinc_oecd +
    sex + age + ethnicity + education + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + gor_dv + 
    factor(wave),
  data = uk,
  index = "pidp",
  model = "random"
)
```

```{r, echo=FALSE}
stargazer(
  list(M1a, M1b, M1c),
  column.labels = c("M1a", "M1b", "M1c"),
  
  keep = c("log_hhnetinc_oecd", "log_hhgrsinc_oecd", "lfstat"),
  
  covariate.labels = c(
    "Equivalence household net income (log)",
    "Equivalence household gross income (log)",
    "Full-time employed (Ref. Retired)",
    "Part-time employed",
    "Self-employed",
    "Unemployed",
    "Inactive"
  ),
  
  add.lines = list(
    c("Controls", "No", "Yes", "Yes")
  ),
  
  notes = "Controls include sex, age, educational attainment, ethnicity, marital status, household income, labor market status, number of children, region, and wave.",
  notes.append = FALSE,
  
  align = TRUE,
  type = "text"
)
```

## M2 (Means-tested benefits)

```{r}
# M2 (Means-tested) ----
## M2a ----
M2a <- plm(
  rel_happy ~ benefit_MT,
  data = uk,
  index = "pidp",
  model = "random"
)


## M2b ----
M2b <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrsinc_oecd +
    sex + age + ethnicity + education + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + gor_dv + 
    factor(wave),
  data = uk,
  index = "pidp",
  model = "random"
)
```

```{r, echo=FALSE}
stargazer(
  list(M2a, M2b),
  column.labels = c("M2a", "M2b"),
  
  keep = c("benefit_MT","log_hhgrsinc_oecd", "lfstat"),
  
  covariate.labels = c(
    "Means-tested benefit receipt (0/1)",
    "Equivalence household gross income (log)",
    "Full-time employed (Ref. Retired)",
    "Part-time employed",
    "Self-employed",
    "Unemployed",
    "Inactive"
  ),
  
  add.lines = list(
    c("Controls", "No", "Yes")
  ),
  
  notes = "Controls include sex, age, educational attainment, ethnicity, marital status, household income, labor market status, number of children, region, and wave.",
  notes.append = FALSE,
  
  align = TRUE,
  type = "text"
)

```

# M3 (In-work)

```{r}
# M3 (In-work) ----
uk_emp <- uk %>%
  filter(
    lfstat %in% c(
      "Full-time employed",
      "Part-time employed",
      "Self-employed"
    )
  )

## M3a ----
M3a <- plm(
  rel_happy ~ benefit_MT,
  data = uk_emp,
  index = "pidp",
  model = "random"
)


## M3b ----
M3b <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrsinc_oecd +
    sex + age + ethnicity + education + 
    relstat2 + lfstat + nchild + gor_dv + 
    factor(wave),
  data = uk_emp,
  index = "pidp",
  model = "random"
)
```

```{r, echo=FALSE}
stargazer(
  list(M3a, M3b),
  column.labels = c("M3a", "M3b"),
  
  keep = c("benefit_MT","log_hhgrsinc_oecd", "lfstat"),
  
  covariate.labels = c(
    "Means-tested benefit receipt (0/1)",
    "Equivalence household gross income (log)",
    "Part-time employed (Ref. Full-time-employed)",
    "Self-employed"
  ),
  
  add.lines = list(
    c("Controls", "No", "Yes")
  ),
  
  notes = "Controls include sex, age, educational attainment, ethnicity, marital status, household income, labor market status, number of children, region, and wave.",
  notes.append = FALSE,
  
  align = TRUE,
  type = "text"
)

```

## M4 (Out-of-work)

```{r}
uk_unemp <- uk %>%
  filter(
    lfstat %in% c(
      "Unemployed",
      "Retired",
      "Inactive"
    )
  )

## M4a ----
M4a <- plm(
  rel_happy ~ benefit_MT,
  data = uk_unemp,
  index = "pidp",
  model = "random"
)


## M4b ----
M4b <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrsinc_oecd +
    sex + age + ethnicity + education + 
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild + gor_dv + 
    factor(wave),
  data = uk_unemp,
  index = "pidp",
  model = "random"
)

```

```{r, echo=FALSE}
stargazer(
  list(M4a, M4b),
  column.labels = c("M4a", "M4b"),
  
  keep = c("benefit_MT","log_hhgrsinc_oecd", "lfstat"),
  
  covariate.labels = c(
    "Means-tested benefit receipt (0/1)",
    "Equivalence household gross income (log)",
    "Unemployed (Ref. Inactive)",
    "Retired"
  ),
  
  add.lines = list(
    c("Controls", "No", "Yes")
  ),
  
  notes = "Controls include sex, age, educational attainment, ethnicity, marital status, household income, labor market status, number of children, region, and wave.",
  notes.append = FALSE,
  
  align = TRUE,
  type = "text"
)
```

## M5 (Men)

```{r}
# M5 (Men) ----
uk_men <- uk %>%
  filter(sex == "Male")

## M5a ----
M5a <- plm(
  rel_happy ~ benefit_MT,
  data = uk_men,
  index = "pidp",
  model = "random"
)


## M5b ----
M5b <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrsinc_oecd + 
    age + ethnicity + education + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + gor_dv + 
    factor(wave),
  data = uk_men,
  index = "pidp",
  model = "random"
)

```

```{r, echo=FALSE}
stargazer(
  list(M5a, M5b),
  column.labels = c("M5a", "M5b"),
  
  keep = c("benefit_MT","log_hhgrsinc_oecd", "lfstat"),
  
  covariate.labels = c(
    "Means-tested benefit receipt (0/1)",
    "Equivalence household gross income (log)",
    "Full-time employed (Ref. Retired)",
    "Part-time employed",
    "Self-employed",
    "Unemployed",
    "Inactive"
  ),
  
  add.lines = list(
    c("Controls", "No", "Yes")
  ),
  
  notes = "Controls include age, educational attainment, ethnicity, marital status, household income, labor market status, number of children, region, and wave.",
  notes.append = FALSE,
  
  align = TRUE,
  type = "text"
)

```

## M6 (Women)

```{r}
# M6 (Woman) ----
uk_women <- uk %>%
  filter(sex == "Female")

## M6a ----
M6a <- plm(
  rel_happy ~ benefit_MT,
  data = uk_women,
  index = "pidp",
  model = "random"
)


## M6b ----
M6b <- plm(
  rel_happy ~ benefit_MT +
    log_hhgrsinc_oecd + 
    age + ethnicity + education + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + gor_dv + 
    factor(wave),
  data = uk_women,
  index = "pidp",
  model = "random"
)
```

```{r, echo=FALSE}
stargazer(
  list(M6a, M6b),
  column.labels = c("M6a", "M6b"),
  
  keep = c("benefit_MT","log_hhgrsinc_oecd", "lfstat"),
  
  covariate.labels = c(
    "Means-tested benefit receipt (0/1)",
    "Equivalence household gross income (log)",
    "Full-time employed (Ref. Retired)",
    "Part-time employed",
    "Self-employed",
    "Unemployed",
    "Inactive"
  ),
  
  add.lines = list(
    c("Controls", "No", "Yes")
  ),
  
  notes = "Controls include age, educational attainment, ethnicity, marital status, household income, labor market status, number of children, region, and wave.",
  notes.append = FALSE,
  
  align = TRUE,
  type = "text"
)
```

### Bonus: M10 (Dyadic Adjustment Scale: Relationship satisfaction subscale)

```{r}
# M10 (Bonus) (DAS) ----
## M10a ----
M10a <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrsinc_oecd +
    sex + age + ethnicity + education + 
    relstat2 + relevel(lfstat, ref = "Retired") + nchild + gor_dv + 
    factor(wave),
  data = uk,
  index = "pidp",
  model = "random"
)


## M10b (In-work) ----
M10b <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrsinc_oecd +
    sex + age + ethnicity + education + 
    relstat2 + lfstat + nchild + gor_dv + 
    factor(wave),
  data = uk_emp,
  index = "pidp",
  model = "random"
)

## M10c (Out-of-work) ----
M10c <- plm(
  DAS_rel_sat ~ benefit_MT +
    log_hhgrsinc_oecd +
    sex + age + ethnicity + education + 
    relstat2 + relevel(lfstat, ref = "Inactive") + nchild + gor_dv + 
    factor(wave),
  data = uk_unemp,
  index = "pidp",
  model = "random"
)
```



```{r, echo=FALSE}
stargazer(list(M10a, M10b, M10c),
          
          column.labels=c("M10a (all)", "M10b (In-work)", "M10c (Out-of-work)"
          ),
          add.lines = list(
            c("Controls", "Yes", "Yes", "Yes")
          ),
          
          align=TRUE,
          type = "text")
```
